export const qs = [
  {
    id: 'uKFuU7VeQ1',
    logs: null,
    logsPage: null,
    name: 'Điền từ tiếng anh tương ứng',
    numberQuestion: 1,
    page: 1,
    questionAudio: '',
    questionContent: '',
    questionImage: '',
    questionTitle: '',
    questionVideo: '',
    questions: [
      {
        id: 804,
        content: 'thông minh',
        mediaUri: '',
        answers: [{ id: 'answer-804-0', content: 'clever', contentShowAnswer: 'clever - /ˈklɛvər/ - thông minh' }],
        userAnswers: [{ answerAudio: '', answerImage: '', answerVideo: '', content: '', id: 'answer-804-0', isCorrect: null, left: null, right: null }],
      },
    ],
    type: 'write',
    typeInteractive: 'question',
    isMatchingImage: false,
  },
  {
    id: 'LZTbuQMDNh',
    logs: null,
    logsPage: null,
    name: 'Điền từ tiếng anh tương ứng',
    numberQuestion: 1,
    page: 1,
    questionAudio: '',
    questionContent: '',
    questionImage: '',
    questionTitle: '',
    questionVideo: '',
    questions: [
      {
        id: 823,
        content: '',
        mediaUri:
          'https://media.istockphoto.com/id/2163774479/fr/photo/a-child-eye-looking-through-a-hole-on-a-cardboard-box-concept-of-spy-and-stalker.webp?a=1&b=1&s=612x612&w=0&k=20&c=EMBSP7ueZWuOZmjAN0QrDw_-oMR7_495yqDJNMRI2gY=',
        answers: [{ id: 'answer-823-0', content: 'reserved', contentShowAnswer: 'reserved - /rɪˈzɜːrvd/ - kín đáo, dè dặt' }],
        userAnswers: [{ answerAudio: '', answerImage: '', answerVideo: '', content: '', id: 'answer-823-0', isCorrect: null, left: null, right: null }],
      },
    ],
    type: 'write',
    typeInteractive: 'question',
    isMatchingImage: false,
  },
  {
    id: 'DVMDOJdLxS',
    logs: null,
    logsPage: null,
    name: 'Điền từ tiếng anh tương ứng',
    numberQuestion: 1,
    page: 1,
    questionAudio: '',
    questionContent: '',
    questionImage: '',
    questionTitle: '',
    questionVideo: '',
    questions: [
      {
        id: 848,
        content: 'lười biếng',
        mediaUri: '',
        answers: [{ id: 'answer-848-0', content: 'lazy', contentShowAnswer: 'lazy - /ˈleɪzi/ - lười biếng' }],
        userAnswers: [{ answerAudio: '', answerImage: '', answerVideo: '', content: '', id: 'answer-848-0', isCorrect: null, left: null, right: null }],
      },
    ],
    type: 'write',
    typeInteractive: 'question',
    isMatchingImage: false,
  },
  {
    id: 'QIMNR3P7ex',
    logs: null,
    logsPage: null,
    name: 'So sánh và chọn đáp án chính xác.',
    numberQuestion: 1,
    page: 1,
    questionAudio: '',
    questionContent: '',
    questionImage: '',
    questionTitle: '',
    questionVideo: '',
    questions: [
      {
        id: 849,
        idLeft: '3',
        keyLeft: 'mediaUri',
        indexWord: 3,
        leftContent:
          'https://media.istockphoto.com/id/1301529333/fr/photo/couples-matures-espi%C3%A8gles-ferroutage-en-jour-dhiver.webp?a=1&b=1&s=612x612&w=0&k=20&c=w3_jvxvBziRcGa-7PMI8WH_XEvHlFWFK9OBwpv5yuVk=',
        titleLeft: 'Hình ảnh',
        idRight: '3',
        rightContent: 'loving',
        titleRight: 'Từ',
        keyRight: 'word',
        answerText: 'loving - /ˈlʌvɪŋ/ - âu yếm, đằm thắm',
        answers: [
          { id: 'answer-849-true', content: 'Đúng', isCorrect: true },
          { id: 'answer-849-false', content: 'Sai', isCorrect: false },
        ],
        userAnswers: [],
      },
    ],
    type: 'chooseAnswers',
    typeInteractive: 'question',
    isMatchingImage: false,
  },
  {
    id: 'UMAbWoH8hK',
    logs: null,
    logsPage: null,
    name: 'Điền từ tiếng anh tương ứng',
    numberQuestion: 1,
    page: 1,
    questionAudio: '',
    questionContent: '',
    questionImage: '',
    questionTitle: '',
    questionVideo: '',
    questions: [
      {
        id: 806,
        content: 'nhát gan',
        mediaUri: '',
        answers: [{ id: 'answer-806-0', content: 'cowardly', contentShowAnswer: 'cowardly - /ˈkaʊərlidli/ - nhát gan' }],
        userAnswers: [{ answerAudio: '', answerImage: '', answerVideo: '', content: '', id: 'answer-806-0', isCorrect: null, left: null, right: null }],
      },
    ],
    type: 'write',
    typeInteractive: 'question',
    isMatchingImage: false,
  },
  {
    id: 'iNjuAPmsEJ',
    logs: null,
    logsPage: null,
    name: 'So sánh và chọn đáp án chính xác.',
    numberQuestion: 1,
    page: 1,
    questionAudio: '',
    questionContent: '',
    questionImage: '',
    questionTitle: '',
    questionVideo: '',
    questions: [
      {
        id: 836,
        idLeft: '5',
        keyLeft: 'mediaUri',
        indexWord: 5,
        leftContent: 'https://media.istockphoto.com/id/157418272/fr/photo/scolded-par-le-patron.webp?a=1&b=1&s=612x612&w=0&k=20&c=7VnQuj2e5t_oG5BivE59hlhoYZ-MYF6BuO8uGjNgZbw=',
        titleLeft: 'Hình ảnh',
        idRight: '4',
        rightContent: 'tolerant',
        titleRight: 'Từ',
        keyRight: 'word',
        answerText: 'bossy - /ˈbɔsi/ - hống hách, hách dịch',
        answers: [
          { id: 'answer-836-true', content: 'Đúng', isCorrect: false },
          { id: 'answer-836-false', content: 'Sai', isCorrect: true },
        ],
        userAnswers: [],
      },
    ],
    type: 'chooseAnswers',
    typeInteractive: 'question',
    isMatchingImage: false,
  },
  {
    id: 'OH91kCa641',
    logs: null,
    logsPage: null,
    name: 'Điền từ tiếng anh tương ứng',
    numberQuestion: 1,
    page: 1,
    questionAudio: '',
    questionContent: '',
    questionImage: '',
    questionTitle: '',
    questionVideo: '',
    questions: [
      {
        id: 850,
        content: 'lạc quan',
        mediaUri: '',
        answers: [{ id: 'answer-850-0', content: 'optimistic', contentShowAnswer: 'optimistic - /ˌɒptɪˈmɪstɪk/ - lạc quan' }],
        userAnswers: [{ answerAudio: '', answerImage: '', answerVideo: '', content: '', id: 'answer-850-0', isCorrect: null, left: null, right: null }],
      },
    ],
    type: 'write',
    typeInteractive: 'question',
    isMatchingImage: false,
  },
  {
    id: 'N2lVg1lpVa',
    logs: null,
    logsPage: null,
    name: 'So sánh và chọn đáp án chính xác.',
    numberQuestion: 1,
    page: 1,
    questionAudio: '',
    questionContent: '',
    questionImage: '',
    questionTitle: '',
    questionVideo: '',
    questions: [
      {
        id: 832,
        idLeft: '4',
        keyLeft: 'word',
        indexWord: 4,
        leftContent: 'tolerant',
        titleLeft: 'Từ',
        idRight: '4',
        rightContent: 'khoan dung',
        titleRight: 'Nghĩa',
        keyRight: 'translate',
        answerText: 'tolerant - /ˈtɒlərənt/ - khoan dung',
        answers: [
          { id: 'answer-832-true', content: 'Đúng', isCorrect: true },
          { id: 'answer-832-false', content: 'Sai', isCorrect: false },
        ],
        userAnswers: [],
      },
    ],
    type: 'chooseAnswers',
    typeInteractive: 'question',
    isMatchingImage: false,
  },
  {
    id: 'Wr5Nq0Q3oC',
    logs: null,
    logsPage: null,
    name: 'Điền từ tiếng anh tương ứng',
    numberQuestion: 1,
    page: 1,
    questionAudio: '',
    questionContent: '',
    questionImage: '',
    questionTitle: '',
    questionVideo: '',
    questions: [
      {
        id: 809,
        content: 'thân thiện',
        mediaUri: '',
        answers: [{ id: 'answer-809-0', content: 'friendly', contentShowAnswer: 'friendly - /ˈfrɛndli/ - thân thiện' }],
        userAnswers: [{ answerAudio: '', answerImage: '', answerVideo: '', content: '', id: 'answer-809-0', isCorrect: null, left: null, right: null }],
      },
    ],
    type: 'write',
    typeInteractive: 'question',
    isMatchingImage: false,
  },
  {
    id: '2sk8biDZFW',
    logs: null,
    logsPage: null,
    name: 'Nối nghĩa của từ với từ tương ứng',
    numberQuestion: 1,
    page: 1,
    questionAudio: '',
    questionContent: '',
    questionImage: '',
    questionTitle: '',
    questionVideo: '',
    questions: [
      {
        dataLeft: [
          { answerAudio: null, answerVideo: '', index: 1, key: 842, id: 'NaFCWaiVNV', content: 'gentle', answerImage: '' },
          { answerAudio: null, answerVideo: '', index: 0, key: 802, id: 'EackL6CCd9', content: 'careless', answerImage: '' },
          { answerAudio: null, answerVideo: '', index: 3, key: 801, id: 'gnu6eLMtkp', content: 'bright', answerImage: '' },
          { answerAudio: null, answerVideo: '', index: 2, key: 846, id: 'm9CTx72QII', content: 'industrious', answerImage: '' },
        ],
        dataRight: [
          { answerAudio: null, answerVideo: '', index: 0, key: 802, id: 'TnQ8BdlUJ1', content: 'bất cần, cầu thả', answerImage: '' },
          { answerAudio: null, answerVideo: '', index: 3, key: 801, id: 'KPfG9PISPj', content: 'sáng dạ, thông minh', answerImage: '' },
          { answerAudio: null, answerVideo: '', index: 1, key: 842, id: 'WJ93jQPYJY', content: 'hiền lành, dịu dàng, hòa nhã', answerImage: '' },
          { answerAudio: null, answerVideo: '', index: 2, key: 846, id: 'yuQQrNaN5z', content: 'cần cù, siêng năng, chăm chỉ', answerImage: '' },
        ],
        userAnswers: [],
      },
    ],
    type: 'matching',
    typeInteractive: 'question',
    isMatchingImage: false,
  },
  {
    id: 'yEZQYz5RQm',
    logs: null,
    logsPage: null,
    name: 'Điền từ tiếng anh tương ứng',
    numberQuestion: 1,
    page: 1,
    questionAudio: '',
    questionContent: '',
    questionImage: '',
    questionTitle: '',
    questionVideo: '',
    questions: [
      {
        id: 815,
        content: '',
        mediaUri:
          'https://media.istockphoto.com/id/1328411209/fr/photo/jeune-homme-barbu-et-son-chien-se-donnant-cinq-%C3%A0-lautre-au-camping.webp?a=1&b=1&s=612x612&w=0&k=20&c=3SSw0NmFsE2eJRwpkp8U3Zxg0-SoNA5AgADBIxnL9NE=',
        answers: [{ id: 'answer-815-0', content: 'loyal', contentShowAnswer: 'loyal - /ˈlɔɪəl/ - trung thành, trung nghĩa' }],
        userAnswers: [{ answerAudio: '', answerImage: '', answerVideo: '', content: '', id: 'answer-815-0', isCorrect: null, left: null, right: null }],
      },
    ],
    type: 'write',
    typeInteractive: 'question',
    isMatchingImage: false,
  },
  {
    id: 'TgPt4NLXoA',
    logs: null,
    logsPage: null,
    name: 'So sánh và chọn đáp án chính xác.',
    numberQuestion: 1,
    page: 1,
    questionAudio: '',
    questionContent: '',
    questionImage: '',
    questionTitle: '',
    questionVideo: '',
    questions: [
      {
        id: 855,
        idLeft: '8',
        keyLeft: 'word',
        indexWord: 8,
        leftContent: 'heartless',
        titleLeft: 'Từ',
        idRight: '5',
        rightContent: 'khoan dung',
        titleRight: 'Nghĩa',
        keyRight: 'translate',
        answerText: 'heartless - /ˈhɑːrt.ləs/ - vô tâm, nhẫn tâm',
        answers: [
          { id: 'answer-855-true', content: 'Đúng', isCorrect: false },
          { id: 'answer-855-false', content: 'Sai', isCorrect: true },
        ],
        userAnswers: [],
      },
    ],
    type: 'chooseAnswers',
    typeInteractive: 'question',
    isMatchingImage: false,
  },
  {
    id: 'E8ju1WKmaX',
    logs: null,
    logsPage: null,
    name: 'So sánh và chọn đáp án chính xác.',
    numberQuestion: 1,
    page: 1,
    questionAudio: '',
    questionContent: '',
    questionImage: '',
    questionTitle: '',
    questionVideo: '',
    questions: [
      {
        id: 819,
        idLeft: '2',
        keyLeft: 'spelling',
        indexWord: 2,
        leftContent: '/ˈnæsti/',
        titleLeft: 'Phiên âm',
        idRight: '2',
        rightContent: 'nasty',
        titleRight: 'Từ',
        keyRight: 'word',
        answerText: 'nasty - /ˈnæsti/ - bẩn thỉu, thô tục, cáu kỉnh',
        answers: [
          { id: 'answer-819-true', content: 'Đúng', isCorrect: true },
          { id: 'answer-819-false', content: 'Sai', isCorrect: false },
        ],
        userAnswers: [],
      },
    ],
    type: 'chooseAnswers',
    typeInteractive: 'question',
    isMatchingImage: false,
  },
  {
    id: 'd77AWJtKck',
    logs: null,
    logsPage: null,
    name: 'Nối ảnh với từ có nghĩa tương ứng',
    numberQuestion: 1,
    page: 1,
    questionAudio: '',
    questionContent: '',
    questionImage: '',
    questionTitle: '',
    questionVideo: '',
    questions: [
      {
        dataLeft: [
          {
            answerAudio: null,
            answerVideo: '',
            index: 0,
            key: 797,
            id: 'hD8OhnHVgf',
            content:
              'https://media.istockphoto.com/id/1511226415/fr/photo/lib%C3%A9rez-le-potentiel-de-r%C3%A9ussite-de-lentreprise-les-fl%C3%A9chettes-et-les-fl%C3%A9chettes-ciblent-la.webp?a=1&b=1&s=612x612&w=0&k=20&c=8GWIfYa_hLpcDew1HH1JRDRZ4sYN9WWRnV2O3UFLLWg=',
            answerImage:
              'https://media.istockphoto.com/id/1511226415/fr/photo/lib%C3%A9rez-le-potentiel-de-r%C3%A9ussite-de-lentreprise-les-fl%C3%A9chettes-et-les-fl%C3%A9chettes-ciblent-la.webp?a=1&b=1&s=612x612&w=0&k=20&c=8GWIfYa_hLpcDew1HH1JRDRZ4sYN9WWRnV2O3UFLLWg=',
            isTest: true,
          },
          {
            answerAudio: null,
            answerVideo: '',
            index: 3,
            key: 852,
            id: 'zTXACORHcM',
            content:
              'https://media.istockphoto.com/id/1816883726/fr/photo/le-menuisier-apporte-les-derni%C3%A8res-corrections-sur-le-polissage-de-la-table-ronde.webp?a=1&b=1&s=612x612&w=0&k=20&c=UfnJlGoWej88N2pjSHB1Uzdos-u-7x0CjC3zCCoAoJg=',
            answerImage:
              'https://media.istockphoto.com/id/1816883726/fr/photo/le-menuisier-apporte-les-derni%C3%A8res-corrections-sur-le-polissage-de-la-table-ronde.webp?a=1&b=1&s=612x612&w=0&k=20&c=UfnJlGoWej88N2pjSHB1Uzdos-u-7x0CjC3zCCoAoJg=',
            isTest: true,
          },
          {
            answerAudio: null,
            answerVideo: '',
            index: 2,
            key: 840,
            id: 'DvCmBM7154',
            content:
              'https://media.istockphoto.com/id/1816901423/fr/photo/jeune-femme-triste-regardant-ailleurs-dans-le-salon-%C3%A0-la-maison.webp?a=1&b=1&s=612x612&w=0&k=20&c=bcb0VGVrdonBxTS8fwCgZQCqjyHUJTbVRxvTPih8WGE=',
            answerImage:
              'https://media.istockphoto.com/id/1816901423/fr/photo/jeune-femme-triste-regardant-ailleurs-dans-le-salon-%C3%A0-la-maison.webp?a=1&b=1&s=612x612&w=0&k=20&c=bcb0VGVrdonBxTS8fwCgZQCqjyHUJTbVRxvTPih8WGE=',
            isTest: true,
          },
          {
            answerAudio: null,
            answerVideo: '',
            index: 1,
            key: 857,
            id: 'niwPbi7rmH',
            content:
              'https://media.istockphoto.com/id/666073502/fr/photo/banquier-avide-ex%C3%A9cutif-ceo-patron-entreprise-employ%C3%A9-cherche-homme-dr%C3%B4le-d%C3%A9tenant-des-billets.webp?a=1&b=1&s=612x612&w=0&k=20&c=BGL4j7kfTx1s3w3AIX3yoRmbWJXo6IxLnu7kxctHVQ8=',
            answerImage:
              'https://media.istockphoto.com/id/666073502/fr/photo/banquier-avide-ex%C3%A9cutif-ceo-patron-entreprise-employ%C3%A9-cherche-homme-dr%C3%B4le-d%C3%A9tenant-des-billets.webp?a=1&b=1&s=612x612&w=0&k=20&c=BGL4j7kfTx1s3w3AIX3yoRmbWJXo6IxLnu7kxctHVQ8=',
            isTest: true,
          },
        ],
        dataRight: [
          { answerAudio: null, answerVideo: '', index: 0, key: 797, id: 'nmvj5bVuBw', content: 'ambitious', answerImage: '' },
          { answerAudio: null, answerVideo: '', index: 1, key: 857, id: 'jnCjoZKsY6', content: 'stingy', answerImage: '' },
          { answerAudio: null, answerVideo: '', index: 3, key: 852, id: '63MLDmrBc3', content: 'picky', answerImage: '' },
          { answerAudio: null, answerVideo: '', index: 2, key: 840, id: 'FcctMhFqps', content: 'dull', answerImage: '' },
        ],
        userAnswers: [],
      },
    ],
    type: 'matching',
    typeInteractive: 'question',
    isMatchingImage: true,
  },
  {
    id: 'lYeCsdcrMv',
    logs: null,
    logsPage: null,
    name: 'So sánh và chọn đáp án chính xác.',
    numberQuestion: 1,
    page: 1,
    questionAudio: '',
    questionContent: '',
    questionImage: '',
    questionTitle: '',
    questionVideo: '',
    questions: [
      {
        id: 822,
        idLeft: '0',
        keyLeft: 'mediaUri',
        indexWord: 0,
        leftContent:
          'https://media.istockphoto.com/id/1761327319/fr/photo/une-aide-soignante-%C3%A0-domicile-parle-%C3%A0-une-femme-%C3%A2g%C3%A9e-dans-une-maison-de-soins-infirmiers.webp?a=1&b=1&s=612x612&w=0&k=20&c=Hu1plpGUv7du_f3S94O8GDqJyKTXhDNxm1JcoZ33Uh0=',
        titleLeft: 'Hình ảnh',
        idRight: '0',
        rightContent: 'reliable',
        titleRight: 'Từ',
        keyRight: 'word',
        answerText: 'reliable - /rɪˈlaɪəbl/ - chín chắn, đáng tin cậy',
        answers: [
          { id: 'answer-822-true', content: 'Đúng', isCorrect: true },
          { id: 'answer-822-false', content: 'Sai', isCorrect: false },
        ],
        userAnswers: [],
      },
    ],
    type: 'chooseAnswers',
    typeInteractive: 'question',
    isMatchingImage: false,
  },
  {
    id: 'UsRqjmjv4k',
    logs: null,
    logsPage: null,
    name: 'Điền từ tiếng anh tương ứng',
    numberQuestion: 1,
    page: 1,
    questionAudio: '',
    questionContent: '',
    questionImage: '',
    questionTitle: '',
    questionVideo: '',
    questions: [
      {
        id: 817,
        content: '',
        mediaUri:
          'https://media.istockphoto.com/id/1054382672/fr/photo/homme-daffaires-avare-avide-jeune-tenant-tirelire.webp?a=1&b=1&s=612x612&w=0&k=20&c=f53OqWXyqOwBO96aOtXUPegc3S2eZsyU-D__eGLu3HI=',
        answers: [{ id: 'answer-817-0', content: 'mean', contentShowAnswer: 'mean - /miːn/ - keo kiệt' }],
        userAnswers: [{ answerAudio: '', answerImage: '', answerVideo: '', content: '', id: 'answer-817-0', isCorrect: null, left: null, right: null }],
      },
    ],
    type: 'write',
    typeInteractive: 'question',
    isMatchingImage: false,
  },
  {
    id: 'Ud5BoJCncx',
    logs: null,
    logsPage: null,
    name: 'Điền từ tiếng anh tương ứng',
    numberQuestion: 1,
    page: 1,
    questionAudio: '',
    questionContent: '',
    questionImage: '',
    questionTitle: '',
    questionVideo: '',
    questions: [
      {
        id: 798,
        content: '',
        mediaUri: 'https://media.istockphoto.com/id/1510831626/fr/photo/vivre-heureux-pour-toujours.webp?a=1&b=1&s=612x612&w=0&k=20&c=RgLcswwUvTWqa7vSLZcOanpzeJXH3FayMqt_J1R80dM=',
        answers: [{ id: 'answer-798-0', content: 'amusing', contentShowAnswer: 'amusing - /əˈmjuːzɪŋ/ - làm cho buồn cười' }],
        userAnswers: [{ answerAudio: '', answerImage: '', answerVideo: '', content: '', id: 'answer-798-0', isCorrect: null, left: null, right: null }],
      },
    ],
    type: 'write',
    typeInteractive: 'question',
    isMatchingImage: false,
  },
  {
    id: 'S8IB1t5drC',
    logs: null,
    logsPage: null,
    name: 'So sánh và chọn đáp án chính xác.',
    numberQuestion: 1,
    page: 1,
    questionAudio: '',
    questionContent: '',
    questionImage: '',
    questionTitle: '',
    questionVideo: '',
    questions: [
      {
        id: 812,
        idLeft: '7',
        keyLeft: 'mediaUri',
        indexWord: 7,
        leftContent:
          'https://media.istockphoto.com/id/2014717779/fr/photo/une-femme-%C3%A2g%C3%A9e-handicap%C3%A9e-passe-du-temps-avec-son-petit-enfant-%C3%A0-la-maison.webp?a=1&b=1&s=612x612&w=0&k=20&c=70Cbxc3lnPnqkrPZZI-FOVmlL65FlhZlEi_Q2qbrwB4=',
        titleLeft: 'Hình ảnh',
        idRight: '5',
        rightContent: 'bossy',
        titleRight: 'Từ',
        keyRight: 'word',
        answerText: 'sensitive - /ˈsɛnsɪtɪv/ - nhạy cảm, có sự cảm thông',
        answers: [
          { id: 'answer-812-true', content: 'Đúng', isCorrect: false },
          { id: 'answer-812-false', content: 'Sai', isCorrect: true },
        ],
        userAnswers: [],
      },
    ],
    type: 'chooseAnswers',
    typeInteractive: 'question',
    isMatchingImage: false,
  },
  {
    id: 'mzkXpO80r5',
    logs: null,
    logsPage: null,
    name: 'Nối nghĩa của từ với từ tương ứng',
    numberQuestion: 1,
    page: 1,
    questionAudio: '',
    questionContent: '',
    questionImage: '',
    questionTitle: '',
    questionVideo: '',
    questions: [
      {
        dataLeft: [
          { answerAudio: null, answerVideo: '', index: 0, key: 841, id: 'NGZu5xEvKu', content: 'garrulous', answerImage: '' },
          { answerAudio: null, answerVideo: '', index: 2, key: 825, id: 'r3bB1yLLkY', content: 'selfish', answerImage: '' },
          { answerAudio: null, answerVideo: '', index: 1, key: 827, id: 'u1nIhZYDO4', content: 'spiteful', answerImage: '' },
        ],
        dataRight: [
          { answerAudio: null, answerVideo: '', index: 0, key: 841, id: 'FGhTcxAPxB', content: 'nói nhiều, ba hoa, lắm mồm', answerImage: '' },
          { answerAudio: null, answerVideo: '', index: 1, key: 827, id: 'p8qw0AKb0W', content: 'hằn học, đầy thù hận, tỏ ra ác ý', answerImage: '' },
          { answerAudio: null, answerVideo: '', index: 2, key: 825, id: '9s3aQqAm4y', content: 'ích kỷ', answerImage: '' },
        ],
        userAnswers: [],
      },
    ],
    type: 'matching',
    typeInteractive: 'question',
    isMatchingImage: false,
  },
  {
    id: 'B9M2vMUcru',
    logs: null,
    logsPage: null,
    name: 'Điền từ tiếng anh tương ứng',
    numberQuestion: 1,
    page: 1,
    questionAudio: '',
    questionContent: '',
    questionImage: '',
    questionTitle: '',
    questionVideo: '',
    questions: [
      {
        id: 800,
        content: '',
        mediaUri: 'https://media.istockphoto.com/id/527531592/fr/photo/escaladeur-saccroche-%C3%A0-une-falaise.webp?a=1&b=1&s=612x612&w=0&k=20&c=aCHbg0U7LJeW5xYTbJxSGQnx2ZHtvQs5qn-E4vmwZDc=',
        answers: [{ id: 'answer-800-0', content: 'brave', contentShowAnswer: 'brave - /breɪv/ - dũng cảm' }],
        userAnswers: [{ answerAudio: '', answerImage: '', answerVideo: '', content: '', id: 'answer-800-0', isCorrect: null, left: null, right: null }],
      },
    ],
    type: 'write',
    typeInteractive: 'question',
    isMatchingImage: false,
  },
  {
    id: 'uSfkw0DScw',
    logs: null,
    logsPage: null,
    name: 'Điền từ tiếng anh tương ứng',
    numberQuestion: 1,
    page: 1,
    questionAudio: '',
    questionContent: '',
    questionImage: '',
    questionTitle: '',
    questionVideo: '',
    questions: [
      {
        id: 811,
        content: 'rộng lượng, hào phóng',
        mediaUri: '',
        answers: [{ id: 'answer-811-0', content: 'generous', contentShowAnswer: 'generous - /ˈdʒɛnərəs/ - rộng lượng, hào phóng' }],
        userAnswers: [{ answerAudio: '', answerImage: '', answerVideo: '', content: '', id: 'answer-811-0', isCorrect: null, left: null, right: null }],
      },
    ],
    type: 'write',
    typeInteractive: 'question',
    isMatchingImage: false,
  },
  {
    id: 'w4f6IXpbgf',
    logs: null,
    logsPage: null,
    name: 'So sánh và chọn đáp án chính xác.',
    numberQuestion: 1,
    page: 1,
    questionAudio: '',
    questionContent: '',
    questionImage: '',
    questionTitle: '',
    questionVideo: '',
    questions: [
      {
        id: 843,
        idLeft: '1',
        keyLeft: 'spelling',
        indexWord: 1,
        leftContent: '/ˈɡriːdi/',
        titleLeft: 'Phiên âm',
        idRight: '1',
        rightContent: 'greedy',
        titleRight: 'Từ',
        keyRight: 'word',
        answerText: 'greedy - /ˈɡriːdi/ - tham lam',
        answers: [
          { id: 'answer-843-true', content: 'Đúng', isCorrect: true },
          { id: 'answer-843-false', content: 'Sai', isCorrect: false },
        ],
        userAnswers: [],
      },
    ],
    type: 'chooseAnswers',
    typeInteractive: 'question',
    isMatchingImage: false,
  },
  {
    id: 'eRZwoeCuBO',
    logs: null,
    logsPage: null,
    name: 'So sánh và chọn đáp án chính xác.',
    numberQuestion: 1,
    page: 1,
    questionAudio: '',
    questionContent: '',
    questionImage: '',
    questionTitle: '',
    questionVideo: '',
    questions: [
      {
        id: 845,
        idLeft: '6',
        keyLeft: 'mediaUri',
        indexWord: 6,
        leftContent: 'https://media.istockphoto.com/id/1787143140/fr/photo/merci-%C3%A9crit-sur-la-bulle-de-chat.webp?a=1&b=1&s=612x612&w=0&k=20&c=cohcu72AaYMyIWke3fsv4bEYHPSWpaf7AY_uT06DX-o=',
        titleLeft: 'Hình ảnh',
        idRight: '6',
        rightContent: 'grateful',
        titleRight: 'Từ',
        keyRight: 'word',
        answerText: 'grateful - /ˈɡreɪtfəl/ - biết ơn',
        answers: [
          { id: 'answer-845-true', content: 'Đúng', isCorrect: true },
          { id: 'answer-845-false', content: 'Sai', isCorrect: false },
        ],
        userAnswers: [],
      },
    ],
  },
];
